# Site settings
baseurl = "https://moveability.city/"
languageCode = "en-gb"
title = "moveability"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "moveability"
  description = "Active moveability for global cities"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "[This'll take you home](/)"
    #text = "[this'll take you home](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "moveability.city"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Overview"
    portfolio = "Moveability"
    about = "About"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "maps/index.html"
      name = "maps"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Active moveability for global cities"
    subtitle = "Urban moveability"
    buttonText = "move me"


  # Services section
  [params.services]
    enable = true
    title = "Overview"
    subtitle = "Our data sources and principles."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-map-o"
      title = "Open Data"
      description = "We use open data wherever possible, including [Open Street Map](https://openstreetmap.org) for most spatial data, along with global-scale databases of open demographic data to understand urban populations."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-cog"
      title = "Open Source Code"
      description = "Our code is open source, [available](https://github.com/atfutures) on [github](https://github.com/moveability), and we are acknowledged world leaders in [open source transport software](https://ropensci.org)."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Web-based Platforms"
      description = "Instead of bulky, stand-alone platforms, our platforms are all web-based, enabling us to develop highly customised, flexible frameworks that are uniquely tailored to individual applications."
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Moveability"
    subtitle = "So what is moveability?"


    [params.portfolio.modal]
      #client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close Component"


    # About section
  #[params.about]
  #  enable = true
  #  title = "About"
  #  subtitle = "What is moveability?"
  #  #endpoint = "Be part<br>of our<br>story!"
  #  endpoint = "Get your<br>city<br>moving!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    #[[params.about.events]]
    #  img = "people.jpg"
    #  date = "Active Moveability"
    #  title = "Moveability is anything that involves you actively moving yourself."
    #  description = "The primary form of active moveability is and always will be walking. Equal to this in many part of the world is cycling. Yet there are no limits on definitions, and moveability is likely to greatly change in the future, as we invent new forms of individual and collective transport which enhance active moveability."

    #[[params.about.events]]
    #  img = "bldg.jpg"
    #  date = "Urban Moveability"
    #  title = "Our focus in on cities"
    #  description = "While moveability has no scale, we ourselves choose to focus on individual cities."

    #[[params.about.events]]
    #  img = "blue.jpg"
    #  date = "Modes of Moveability"
    #  title = "Walking, cycling, and beyond"
    #  description = "All analyses consider walking and cycling, both as moveability in its own right, and in conjunction with public transport usage. Additional modes of moveability are also considered, and are likely to become increasing important as we invent new ways to actively move."

    #[[params.about.events]]
    #  img = "ghent.jpg"
    #  date = "Urban Analyses"
    #  title = "Moveability of a city"
    #  description = "Our own open source software uses open data to analyse moveability and to deliver the results in an integrated, online platform able to be customised to an individual city's desires, needs, and visions of its own future."


  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      #[[params.clients]]
      #  logo = "envato.jpg"
      #  link = "#"

      #[[params.clients]]
      #  logo = "designmodo.jpg"
      #  link = "#"

      #[[params.clients]]
      #  logo = "themeforest.jpg"
      #  link = "#"

      #[[params.clients]]
      #  logo = "creative-market.jpg"
      #  link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Any questions, comments, queries. Please!"
    buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "mark.padgham@email.com"

    # Success and error message overwrite for async contact form
    # thanks = "Thank you for awesomely contacting us."
    # error = "Message could not be send. Please contact us at mail@example.com instead."

    # [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/moveability"
      title = "github"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/atfutures"
      title = "github"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/moveablecity"
      title = "Twitter"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
